### ISSUE TITLE
Logstash email SMTP options documentation needs work

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-email#24]
(This issue was originally filed by @mefforda-avalon at https://github.com/elastic/logstash/issues/2267)

---

The documentation around custom SMTP connections on the outbound email connector is inadequate and inaccurate.  It appears it is a cut and past from the Ruby Mail documentation and following does not result in a working config.  

More specifically, the options block is listed as an hash, but when using a hash the options are ignored.  If however you encode those options as an array they do seem to work, but there is no example in the documentation that suggests this is the case.  What is there suggests it should be a hash.

I.E.

Documentation suggests that this works:
               options => { "smtpIporHost","gmail.com" }

It does not.

However, this does work
               options =>  [ "smtpIporHost","gmail.com" ]

Also some of the older versions of this documentation are worse and don't even state the config value name correctly instead refer to 'address' while the code clearly references 'smtpIporHost'.

This was tested using 1.4.2

**Comment by purbon** [comment]
A first intent to ge this better just got merged in #29, closing this for now, we could always reopen if the documentation is not good this new way also.
