### ISSUE TITLE
@attachments should allow sprintf values

### ISSUE THREAD

**Issue by wiibaa** [logstash-plugins/logstash-output-email#34]
As found by a user https://discuss.elastic.co/t/dynamic-attachments-to-email-output/41559

the `@attachments` configuration does not compute sprintf values, this is obvious when looking at the code
https://github.com/logstash-plugins/logstash-output-email/blob/v3.0.2/lib/logstash/outputs/email.rb#L135-L137

Current `mail.add_file(fileLocation)` should become  `mail.add_file(event.sprintf(fileLocation))`

This needs _(maybe my own reminder if I found time for a PR)_
- [ ] Fix
- [ ] Test
- [ ] Documentation update

**Comment by jstoja** [comment]
I'm not sure it's something wanted. @jsvd Any idea if the feature would fit into the vision of the output?

**Comment by jsvd** [comment]
closing this as I believe this feature could be misused and abused very easily.
