### ISSUE TITLE
Logstash print "Too many outgoing mail, pleasy try it later"

### ISSUE THREAD

**Issue by maojing0609** [logstash-plugins/logstash-output-email#40]
Hi:
   now,i`m face this issue,also,i can`t receive email,i`m wonder what cause?
     1、too many email in the queue need to send？
     2、it does`t like the smtp server refuse,because when i restart logstash service ,everything go ok!
     thank you!

- Version:  5.0
- Operating System:  centos 7

**Comment by jstoja** [comment]
@maojing0609 Anything useful in the logs? At which frequency do you send emails?

**Comment by jstoja** [comment]
@maojing0609 Any update on this?

**Comment by maojing0609** [comment]
yeah,too many days go,now i forgot it,any questions i'll ask for help
