### ISSUE TITLE
Add html template for emails

### ISSUE THREAD

**Issue by jstoja** [logstash-plugins/logstash-output-email#48]
Hello guys,

I'm currently working on logstash and I'm having pretty huge `htmlbody`s and I was thinking that it could be nice to have an erb or an html template loaded from a file, that would allow people to make fancier emails :)

Would that be something that could be integrated into trunk?

Thanks
Julien

**Comment by jstoja** [comment]
@jsvd ?

**Comment by jsvd** [comment]
@jstoja I really like that idea should be easy to add an option like `erb_template => 'path/to/file.erb'` and have the template load data from each event

**Comment by jordansissel** [comment]
Can we use something like `mustache` instead of `erb`? Erb allows arbitrary ruby code, and mustache does not. For security, mustache is much safer.

Otherwise, +1 on supporting templating, especially for HTML.

**Comment by jstoja** [comment]
Yes, that would be definitely better.
